### ISSUE TITLE
Modrinth 1.20/1.20.1 marking

### ISSUE THREAD

**Issue by kosma** [emmods/quilt_mods#2]
Hi, can you mark the mod as 1.20.x compatible on Modrinth? It works on those versions.

**Comment by triphora** [comment]
Depends which mod. This repo is for about 8 different mods.

**Comment by lewxdev** [comment]
Looking for 1.20 update for DCCH, not sure if it exists in this repo but the source link from Modrinth takes you here

**Comment by kosma** [comment]
Oh damm, sorry, I meant DCCH.

**Comment by triphora** [comment]
Done for DCCH
